### ISSUE TITLE
"Unable to open" error on goto definition on external references

### ISSUE THREAD

**Issue by ssoher** [sublimelsp/LSP-OmniSharp#20]
LSP GoTo definition doesn't open the definition on external references. Tested using Unity game engine. Doesn't matter if I have `omnisharp.enableDecompilationSupport` `true` or `false`.

```
Unable to open /E/project/P/Assets/_game/script/$metadata$/Project/p/Assembly/UnityEngine/CoreModule/Symbol/UnityEngine/Debug.cs
Traceback (most recent call last):
  File "E:\app\Sublime Text\Lib\python33\sublime_plugin.py", line 859, in on_load
    run_view_callbacks('on_load', view_id)
  File "E:\app\Sublime Text\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "E:\app\Sublime Text\Lib\python33\sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "G:\My Drive\backup\Sublime Text\Installed Packages\LSP.sublime-package\boot.py", line 167, in on_load
    if fn == file_name or os.path.samefile(fn, file_name):
  File "./python3.3/ntpath.py", line 603, in samefile
FileNotFoundError: [WinError 3] The system cannot find the path specified: '$metadata$\\Project\\p\\Assembly\\UnityEngine\\CoreModule\\Symbol\\UnityEngine\\Debug.cs'
```

**Comment by rwols** [comment]
Is your folder called “$metadata$“ ?

**Comment by rwols** [comment]
Can you open the LSP Log Panel (from the command palette) and post the exact request to the OmniSharp server and corresponding response here?

**Comment by rwols** [comment]
Just to be clear, you’re trying to goto-def on something internal to Unity?

If so, it seems that $metadata$ is supposed to be a marker to possibly disassemble a Unity DLL. If that’s indeed the case, then I’m not versed well enough in the .NET ecosystem to readily write code to disassemble that DLL. Nonetheless, it should be possible to handle this in a custom on_open_uri_async callback on this plugin side, provided we know how to disassemble C# DLLs.

**Comment by rwols** [comment]
We can look at what the VSCode extension is doing in such cases and translate it to Python

**Comment by ssoher** [comment]
https://github.com/OmniSharp/omnisharp-vscode/blob/77ec34e0080939a02e15a63a06e005f2098134b6/src/features/definitionProvider.ts#L51-L100

Not exactly sure if this is the relevant part in the VSCode source code and how this can be adapted in ST LSP omnisharp. I'm just tired of firing up Visual Studio (not VSCode) whenever I need decompilation, which happens on a daily basis

**Comment by rwols** [comment]
You seem to be right on the mark with that link. Crucially, I think we need to request "metadata info" with a custom request to resolve things: https://github.com/OmniSharp/omnisharp-vscode/blob/77ec34e0080939a02e15a63a06e005f2098134b6/src/omnisharp/utils.ts#L136

Kind of related: https://github.com/microsoft/language-server-protocol/issues/1595
